# 1. Build 
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the projects
COPY . .

#  (Restore & Publish)
RUN dotnet publish "Order.API/Order.API.csproj" -c Release -o /app/out

# 2. Runtime 
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .

# Start the app
ENTRYPOINT ["dotnet", "Order.API.dll"]